version: '3.8'
services:
  xss-retos:
    image: blasillo/xss-retos:latest
    container_name: xss-retos
    ports:
      - "80:3000"
    restart: unless-stopped

  web:
    container_name: whereismywebshell
    image: blasillo/whereismywebshell:latest
    ports:
      - "8080:80"
    restart: unless-stopped